### ISSUE TITLE
WCIII reforged file format

### ISSUE THREAD

**Issue by killsunday** [PBug90/w3gjs#28]
I've been trying to parse files created by WCIII reforged and it's not compatible.  Can we collaborate on improving the parser?  I've never parsed binary formats before, but I can work through it.  

Parsing the header fails really quickly with an offset error, which I assume means the byte counts are off compared to the original file format.

Thoughts?

**Comment by PBug90** [comment]
Can you provide a sample file that we can use a common base? I did not take a look at the Reforged replay files yet, but will do now that you raised this issue and report back on you.

**Comment by killsunday** [comment]
Here is a current one.  

https://twitter.com/JonnyRoot_/status/1191783735475068928?s=20

**Comment by killsunday** [comment]
Here is a new format:

https://www.dropbox.com/s/wl4q5hf72q3qubr/LastReplay.w3g?dl=0

**Comment by PBug90** [comment]
https://github.com/PBug90/w3gjs/tree/feat-reforged-replays

This branch fixes the offset error. It looks like they changed the block size and compression algorithm in some way, so the compressed blocks can not be decompressed with the existing method.

I added two sample tests for reforged replays that can be run in isolation via jest:
https://github.com/PBug90/w3gjs/blob/feat-reforged-replays/test/replays.test.ts#L190
https://github.com/PBug90/w3gjs/blob/feat-reforged-replays/test/replays.test.ts#L194

I will further investigate. If you have an idea please comment aswell.

**Comment by PBug90** [comment]
After futher investigation it looks like they added two more bytes between the blockDecompressedSize indicator and the actual compressed data. I update the branch with a working version that can parse the replay except its actions.

**Comment by killsunday** [comment]
Awesome! I'll pull it today, I was super busy yesterday and didn't get a chance to look at the project yet.

**Comment by PBug90** [comment]
Looks like they added a new action with id 0x7b which is always 18 bytes long (including the action identifier).
I updated the branch again to include this action and the parsing errors seem to have gone. I also reenabled the timeslot-event-emitting in the base parser so the parser output works as expected for reforged replays.

Still have to determine what the new action does though.

**Comment by killsunday** [comment]
I've been trying to figure out what the action is, but I'm super slow at debugging these.  Is it the case for block type 34?

**Comment by PBug90** [comment]
Can you elaborate on what you mean with your question?

**Comment by PBug90** [comment]
I updated the investigation branch and added changed the action 0x7b parsing behaviour to create a buffer instead of just skipping it. This allows filtering for 0x7b actions in a .on('actionblock') event listener callback.

I updated one of the tests to console.log if the parser encounters a 0x7b block in the first reforged replay so that it logs 0x7b as a hex string on the console.

**Comment by killsunday** [comment]
Awesome!  I'll pull that up today.  I was looking at a series of actions that have different "types" and there was a mix of 31 type id and 34 type id.  31 was handled, but 34 was not.

**Comment by iggyfisk** [comment]
Heads up, the latest Reforged build added a completely new set of bytes to the GameMetaData

https://github.com/iggyfisk/w3gjs/commit/62d177a4a0c7725f8c30a128ef52993267980ba9#diff-bc9969e63009b789c7d3e540727ba6fb

Between the `playerList` and `playerSlotRecords` there's a bunch of mystery bytes, followed by *ANOTHER* player listing. This one includes the full battle.net tag (the names in `playerList` have a digit missing), plus some... stuff.

We're pretty sure the optional bytes (`extraLength` and `extra` in my quick fix version) are the players' portraits, with `extraLength == 0` for nothing selected. It would make sense if selected skins are also in there, but we'll get back to you after some experiments.

Mad greetz from https://highper.ch R&D

**Comment by PBug90** [comment]
Is the replay file provided in the diff one that should be correctly parsed with your adjustments?

**Comment by iggyfisk** [comment]
>  I opened a PR but your changes do not seem to parse the file correctly.

That PR is missing the `0x7B` action and the `blockSize` changes in the header, that you have in `feat-reforged-replays`. Which will break old replays. (Also Reforged is at 1.32 now)

Anyway we also figured out that in between `gameName` and `encodedString` there's the string `hunter2` for private custom games, at least in Reforged. This broke private game parsing for us until https://github.com/iggyfisk/w3gjs/commit/7f4f495e2272d27b7cc8c207572ea10ef0ce5d40#diff-bc9969e63009b789c7d3e540727ba6fb

It's not unlikely that it's the same for private games in 1.31 but none of us have it installed anymore.

Wouldn't surprise me if they make more breaking changes before the "release" in a few weeks. Which is going to be a very broken "release" anyway so who knows how much will happen after that. You could hold off on trying to merge stuff until then, we'll keep testing every patch and reverse engineer changes as they happen.

**Comment by PBug90** [comment]
You are right, I merged feat-reforged-replays and it parses the replay successfully now.

Waiting for release seems to be the reasonable way to go. Until then we should use feat-reforged-replays for all reforged-related changes made to the parser and implement decision making logic on how to handle vanilla and reforged replays in the future. I will merge feat-reforged-metadata into feat-reforged-replays and open another PR since that branch name seems to be more reasonable anyway.

**Comment by iggyfisk** [comment]
And would you fancy that, they added another 2 bytes to the new player list
https://github.com/iggyfisk/w3gjs/commit/f83bbbe09827fec2e62796ad298628a9ed04b921#diff-bc9969e63009b789c7d3e540727ba6fb

https://highper.ch requires that we can parse every intermediate version of the replay format, but I could understand if you want to skip everything in between Classic 1.31 -> Reforged release.

**Comment by PBug90** [comment]
Thanks for your updates. I would appreciate if you could file pull requests for the feat-reforged-metadata branch and also provide sample replays in them. I can set up the testing and keep the features updated and the library backwards compatible.

**Comment by iggyfisk** [comment]
I'll prepare a cleaned up version on release

**Comment by PBug90** [comment]
I have updated the feature branch to include a slightly modifed adaptation of your changes and made it backwards-compatible so all tests pass for now.

**Comment by iggyfisk** [comment]
No more format changes yet, will follow up on this on saturday

**Comment by PBug90** [comment]
Since the branch is already up to date and backwards-compatible all I need is a replay file of the latest reforged build so there is a test case covering that buildNumber. If it passes, I will merge the feat-reforged-replays branch and make a new release.

**Comment by PBug90** [comment]
I just released version 1.6.0 which should be compatible with current reforged and all classic replays. Let me know if you have any issues.

**Comment by PBug90** [comment]
Closing this issue as version 2.0 is close to release and version 1 can parse reforged replays properly at the moment. Feel free to open a new issue if you run into problems again.
