### ISSUE TITLE
Feature request. Optional readFileSync in ReplayParser.ts

### ISSUE THREAD

**Issue by Stannnnn** [PBug90/w3gjs#29]
Hello, can we make the readFileSync optional? I'd like to pass the complete replay as string. I'm using a node webserver and already have the replay contents. Don't really wanna write it to a file so that it can be parsed.

https://github.com/PBug90/w3gjs/blob/master/src/ReplayParser.ts#L45

Tried to do it myself but for some reason VS code keeps formatting the entire file differently :)

**Comment by PBug90** [comment]
I do not think that a simple string would work due to encoding, unless it is a hex encoded string.

Did you mean to pass a buffer instead of a string?

**Comment by Stannnnn** [comment]
Ah oops, yep it's a buffer.

**Comment by PBug90** [comment]
I think you could just adjust the parse function so it can take either a buffer or a string and then decide what to do:
if it is a buffer, try to parse it immediately.
if it is a string, try to read a file and then parse the file buffer.

Would you like to create a PR?

**Comment by PBug90** [comment]
Merged with #31 
Release to be done.

**Comment by PBug90** [comment]
Published as 1.4.1.
