### ISSUE TITLE
Action type 0x7a: keyboard event

### ISSUE THREAD

**Issue by Drake53** [PBug90/w3gjs#33]
Not sure what this action does (I suspect it may be related to the new keyboard/oskeytype natives). It appears to always be 21 bytes long (including the action identifier). Example replay here: https://wc3stats.com/games/8632

Edit: can confirm it's for keyboard events. I found that bytes 13-16 is for the oskeytype, and 17-20 is the metakey. For example, when pressing alt+f4, the action block's bytes will end with "0x73 0 0 0 4 0 0 0". I'm still investigating the meaning of the first 12 bytes.

**Comment by PBug90** [comment]
I published 1.5.0 with a basic skip subparser for this action type so parsing a replay file works properly for now.

**Comment by PBug90** [comment]
I assume this issue can be closed. If not, feel free to comment so we can reopen it.
