### ISSUE TITLE
Alphanumeric itemId values

### ISSUE THREAD

**Issue by jblanchette** [PBug90/w3gjs#43]
Hi - thanks for your hard work as always

I've started using the latest `1.6.0` release and I have noticed that `alphanumeric` itemId values might have possibly changed while trying to parse a pre-reforged replay from the last major patch.

I am now getting a value of `19` for the third item in the list pretty consistently when it used to always be marked as `13`  (`0D` in hex)

Following this old guide used to match these values for the much older `1.1.2` release of `w3gjs` I would previously get a value of `13` for the right click - link to format guide: https://github.com/scopatz/w3g/blob/master/w3g_actions.txt#L961

Old w3gjs (1.1.2) version output:  `[ 3, 0, 13, 0 ]`
New w3gs (1.6.0) version output: `[ 3, 0, 19, 0 ]`

---

Do you think these values have changed as a result of the reforged changes?  Or is it possible the new values are being decoded incorrectly?

I can provide an older replay if needed or helpful

Thanks!

**Comment by PBug90** [comment]
If output ist different for the same input replay file then this is definitely not intended behaviour. 

Can you provide a replay file and basic code to see the invalid output?

**Comment by PBug90** [comment]
In an earlier commit, I changed the parsing of the action ids to unsigned integer.
https://github.com/PBug90/w3gjs/commit/7e96e9dab36d3d838a443cf5e024c1b244d48766#diff-599025833dea49f1272ec504708b1bd8

This is probably the reason why you see a different value for the same input.

**Comment by PBug90** [comment]
Released as 1.6.2.

**Comment by jblanchette** [comment]
brilliant work - just tested it out and it gets me the correct values again

thanks so much!
