### ISSUE TITLE
TypeError: Cannot set property 'playerName' of undefined

### ISSUE THREAD

**Issue by Stannnnn** [PBug90/w3gjs#51]
TypeError: Cannot set property 'playerName' of undefined
at /node/classic-chat-bot-node/node_modules/w3gjs/src/W3GReplay.ts:108:61

The replay: https://tft.w3replayers.com/replays/download.php?id=29177

**Comment by PBug90** [comment]
Looks like that replay has one player missing in the GameMetaDataReforged playerList, while the player exists in extraPlayerList. The player's nickname is banani#21111. This is odd and was not observed before. 

I cannot even get it to show up in the actual game. Do you have any more information about this replay?

A possible workaround would be to ignore the ghost player record.

**Comment by Stannnnn** [comment]
Its a custom game: Banjoball, I've seen it parse successfully before although the latest replays seem to throw this error. So if its a specific player that's causing it then that makes sense.

The map: https://www.dropbox.com/s/ioyivpyik1eivla/Banjoball%20v1.22C1%20%5BPROT%5D.w3x?dl=0

Can't seem to get the replay to show up in the actual game either.. Then again none of my replays are..

Guess ignoring the ghost player record sounds good if the rest of the parser doesn't depend on it.

**Comment by PBug90** [comment]
Fixed in 1.7.1.

**Comment by PBug90** [comment]
Closing this issue for now. Feel free to reopen if error occurs again.
