### ISSUE TITLE
Buffer out of bounds while parsing

### ISSUE THREAD

**Issue by jblanchette** [PBug90/w3gjs#55]
Hi there 👋 

I've been seeing this error pop up on a few multiplayer replays as of late:

```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:75:11)
    at Buffer.readUInt8 (internal/buffer.js:243:5)
    at Parser.eval [as compiled] (eval at <anonymous> (eval at otherRunInContext (/jeef/wc3v/node_modules/w3gjs/dist/W3GReplay.umd.js:1:1)), <anonymous>:4:14)
    at Parser.parse (/jeef/wc3v/node_modules/w3gjs/dist/W3GReplay.umd.js:3064:25)
    at W3GReplay.ReplayParser._parseHeader (/jeef/wc3v/node_modules/w3gjs/dist/W3GReplay.umd.js:5075:40)
    at W3GReplay.ReplayParser.parse (/jeef/wc3v/node_modules/w3gjs/dist/W3GReplay.umd.js:5051:18)
    at W3GReplay.parse (/jeef/wc3v/node_modules/w3gjs/dist/W3GReplay.umd.js:5183:36)
    at /jeef/wc3v/wc3v.js:53:29
    at Array.map (<anonymous>)
    at Object.parseReplays (/jeef/wc3v/wc3v.js:41:25) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```

attached is a mzip file with one wc3 replay inside called `bufferissue.w3g`

[bufferissue.zip](https://github.com/PBug90/w3gjs/files/4808656/bufferissue.zip)

system info:

```
node version: v12.18.0

Debian GNU/Linux 9 (stretch)

kernel: 4.9.0-11-amd64
```

on windows 10 using node `v12.16.0` it seems to not error but possibly has some issues with player data as I'm not seeing action blocks for 2 of the 4

Thanks so much for all your work on this 👍  Was wondering if there was anything more information or debugging you'd like me to submit for these errors on replays?

**Comment by PBug90** [comment]
Added as a test case and it seems to work properly even on linux type systems, see the CICD result: https://travis-ci.org/github/PBug90/w3gjs/jobs/700874125

Make sure you use latest version and maybe to to reinstall dependencies from scratch.

**Comment by jblanchette** [comment]
Still stuck on this one - I've tried different versions of node and have re-installed dependencies.  My package-lock.json looks right as well.

Seems to be hitting the error case on a good majority of replays I attempt from online games

**Comment by PBug90** [comment]
Would you mind sharing 2 or 3 additional replays that fail the parsing?

**Comment by jblanchette** [comment]
yes absolutely, thanks for looking into it

here is a zip with three replays that cause the error

file is named `badreplays.zip` and has three replays - `bad1.w3g, bad2.w3g, bad3.w3g`

[badreplays.zip](https://github.com/PBug90/w3gjs/files/4909664/badreplays.zip)

**Comment by PBug90** [comment]
Thank you for providing the replays. I took my time and updated my web app at https://enigmatic-springs-58797.herokuapp.com/ to use the latest w3gjs version and it parses the replays just fine.

Can you share a repository link with a specific commit that does not work properly so I can have a look?

**Comment by jblanchette** [comment]
believe I found the root cause of this and it was an error in how i'm handling the file uploads.  I noticed the md5 hash of the data was different for some files

closing this out for now, sorry for the bother and thanks for the help
