### ISSUE TITLE
Select Subgroup itemId issue

### ISSUE THREAD

**Issue by jblanchette** [PBug90/w3gjs#65]
hi, am working on upgrading to v2 and am running into an issue with the `SelectSubgroupAction` and possibly other actions

the `itemId` is now in the array format of `[ 111, 99, 97, 117 ]` instead of the previous 4-character string encoded format 

example action json

```
 {
  id: 25,
  itemId: [ 111, 99, 97, 117 ],
  objectId1: 18451,
  objectId2: 18457
}
```

believe the previous versions handled this data encoding by doing this: https://github.com/PBug90/w3gjs/blob/1f5c48650cab97505af37c96ac74410416608eb9/src/parsers/formatters.ts#L4-L9

if the above is something you'd prefer we do outside of the parser will happily change to that

thanks!

**Comment by PBug90** [comment]
That new behaviour is correct. The low-level parsers do not make assumptions about the actual meaning of the data, so that was lifted up into the W3GReplay and its corresponding helper classes. 

Also check out the autogenerated docs regarding the actions: https://pbug90.github.io/w3gjs/modules/_parsers_actionparser_.html

I will close the issue. Feel free to reopen if you run into issues.

**Comment by jblanchette** [comment]
am getting back the parsed action from the `ActionParser` but believe the `parseAction` handler is just doing the wrong thing with the data

https://github.com/PBug90/w3gjs/blob/c78a709/src/parsers/ActionParser.ts#L299-L304

the `SelectSubgroupAction` should have `itemId` of  `uaco`  for this example case

**Comment by PBug90** [comment]
The four integers in your array above correspond to the string ocau. The formatter-functionfrom version 1.x above also reversed the string after creating it, resulting in the correct output of uaco.

**Comment by jblanchette** [comment]
I may be able to submit a PR to take on this work if you'd like?

**Comment by PBug90** [comment]
I didnt consider this to be a fixable bug since it refers to the low-level parser, which does not use formatters any longer (in contrast to V1). As a solution you can define your own formatter-function and deal with the data as you please.

**Comment by jblanchette** [comment]
would like you to reconsider it as not a bug due to the data being unusable in its current format.  the four string character codes are a major part of making replays usable

that said I will use a formatter and you're free to close this if you wish

**Comment by PBug90** [comment]
Even though I can understand that this is a step back for you, I would like to keep it as it is at the moment. I want to keep the low level parsers low level and not make any assumptions about the data as long as this is feasable. Therefore the consumer has to decide what to do with the data. The high level parsers can always be used as a reference as to how to use specific interfaces.

I am  closing this for now. Feel free to create a new issue if you need help in the future.

**Comment by jblanchette** [comment]
> Even though I can understand that this is a step back for you

It's an important part of the games internal system and used heavily in the editor as well so it's not just a step backwards for me

I'm not sure the argument holds that this is a problem related to 'low level formatting' because nowhere else would we represent data in a different format than the game uses i.e binary instead of text
