### ISSUE TITLE
Issue due to fitering players by slotStatus > 1

### ISSUE THREAD

**Issue by DavidMente** [PBug90/w3gjs#67]
I have a replay with an issue where the player is not in the `W3GReplay.players` object. The replay fails in `processCommandDataBlock` since the playerId has not been added. I have seen that players are only added to that object depending on their `slotStatus` in `handleBasicReplayInformation`. What does that slotStatus actually mean? If I remove that condition, the replay can be parsed. But it returns a high amount of players. How should we go about this - should we just make the parser more capable to deal with the fact when a player cannot be found? Attached the replay
[ced_vs_lyn.zip](https://github.com/PBug90/w3gjs/files/5714281/ced_vs_lyn.zip)

Edit: Apparently this (and other replays with the same issue) are customs from the new W3C Flobot.exe

**Comment by PBug90** [comment]
I just asked fluxxu (creator of the hostbots) and it seems like Blizzard added special records for LAN games. Those are not part of the parser here yet.

For reference: https://github.com/nielsAD/gowarcraft3/blob/77326e95295636a1d4a60ab253323e65c4e4a8ca/file/w3g/records.go#L786

**Comment by PBug90** [comment]
Should be fixed in v2.2.2

**Comment by DavidMente** [comment]
Fantastic, I have actually noticed that we have the same issue with some old Netease replays so this will most likely also fix that. Currently reparsing 40k+ replays. Very few issues
