### ISSUE TITLE
Parsing of action objectId1 and objectId2 issue

### ISSUE THREAD

**Issue by jblanchette** [PBug90/w3gjs#77]
when parsing actions for `UnitBuildingAbilityActionTargetPositionTargetObjectId` the `objectId1` and `objectId2` field are incorrect - they are always the value `4294967295` in every action

example output

```
{
   "id":18,
   "abilityFlags":0,
   "itemId":[
      3,
      0,
      13,
      0
   ],
   "targetX":-291.32562255859375,
   "targetY":1627.026123046875,
   "objectId1":4294967295,
   "objectId2":4294967295
}
```

example replay file with issue is attached as `replay-object-id-issue.zip` with file `test-ch-movement.w3g`

[replay-object-id-issue.zip](https://github.com/PBug90/w3gjs/files/5745745/replay-object-id-issue.zip)

**Comment by PBug90** [comment]
The value is correct. It represents 0xffffffff.

As per http://w3g.deepnode.de/files/w3g_actions.txt section 0x12 Unit/building ability  (with target position and target object ID)

>  objectID1 == objectID2 == FF FF FF FF for no object (e.g. rally on ground)

**Comment by jblanchette** [comment]
gotcha - found the issue was the old library would return `-1` for both object ids previously. closing thanks
